print('custo do fabricante')
custo_fabricante<-scan()
print('procentagem do distribuidor')
porcentagem_distribuidor<-scan()
print('valor dos impostos')
porcentagem_imposto<-scan()
p_imp<-(porcentagem_imposto*custo_fabricante/100)
p_dist<-(porcentagem_distribuidor*custo_fabricante/100)
valor_total=round(custo_fabricante+p_imp+p_dist,2)
print(valor_total)
