print('faça o input do numero total de eleitores')
total_eleitores<-scan()
print('faça o input dos votos brancos')
votos_brancos<-scan()
print('faça o input dos votos nulos')
votos_nulos<-scan()
print('faça o input dos votos validos')
votos_validos<-scan()
porcentagem_brancos=round(votos_brancos*100/total_eleitores,2)
porcentagem_nulos=round(votos_nulos*100/total_eleitores,2)
percentagem_validos=round(votos_validos*100/total_eleitores,2)
print(paste('votos brancos',porcentagem_brancos,'votos nulos',porcentagem_nulos,'votos valido',percentagem_validos))
